spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_boot_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

client:
  url: http://localhost:8080